name: Test & Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run test
        env:
          CI: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: yarn coverage:report

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      # TODO: find a way to restore artifacts from build
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Deploy CDN
        env:
          QUPLOAD_ACCESS_KEY: ${{ secrets.QUPLOAD_ACCESS_KEY }}
          QUPLOAD_SECRET_KEY: ${{ secrets.QUPLOAD_SECRET_KEY }}
          QUPLOAD_BUCKET: ${{ secrets.QUPLOAD_BUCKET }}
          QUPLOAD_DOMAIN: ${{ secrets.QUPLOAD_DOMAIN }}
          QUPLOAD_ZONE: ${{ secrets.QUPLOAD_ZONE }}
        run: yarn deploy:cdn
      - name: Prepare artifacts
        run: |
          mv ./backend ./backend-build
          mv ./backend-build/build ./backend
          cd backend
          yarn install --production
          cd ..
          tar -cvf dist.tar backend frontend/build/*.*
      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # ssh setups copied from: https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "$SSH_PRIVATE_KEY" > "$SSH_PATH/deploy_key"
          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/deploy_key"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/deploy_key"
          ssh-keyscan -t rsa $SSH_HOST >> "$SSH_PATH/known_hosts"

          scp -i $SSH_PATH/deploy_key ./dist.tar ci@sh.samuraime.com:/www/katana/dist.tar
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /www/katana && tar -xf dist.tar -C ./ && pm2 restart ./process.json"
